const study=window.STUDY,grammars=window.GRAMMAR;
function node(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e}
function rich(e,text){String(text||'').split(/(\*\*.*?\*\*)/g).forEach(t=>e.append(t.startsWith('**')?node('strong','',t.slice(2,-2)):document.createTextNode(t)))}
function grammarCard(g){const card=node('article','grammar-entry');card.append(node('h3','',g.form));if(g.body){for(const line of g.body.split('\n').filter(Boolean)){const p=node('p');rich(p,line);card.append(p)}}else{for(const [label,value] of [['接续',g.connection],['含义',g.meaning],['提示',g.note]]){if(value){const p=node('p');p.append(node('strong','',label+'：'),document.createTextNode(value));card.append(p)}}const ex=node('p','example-ko',g.example);ex.lang='ko';card.append(ex,node('p','',g.translation));for(const e of g.alternate_examples||[])card.append(node('p','example-ko',e.example),node('p','',e.translation))}return card}
function jump(id){if(id==='original-section')$(id).open=true;$(id).scrollIntoView({block:'start',behavior:'smooth'})}
function renderStudy(a){document.body.classList.remove('grammar-view');$('reader').hidden=false;$('grammar-browser').hidden=true;const d=study[a.id];$('original-heading').textContent=a.kind==='dialogue'?'对话原文':'文章原文';$('original-text').replaceChildren();d.original.forEach(t=>{const p=node('p');if(t.speaker)p.append(node('strong','speaker',t.speaker+'：'));const k=node('span','',t.korean);k.lang='ko';p.append(k);$('original-text').append(p)});$('article-grammar').replaceChildren(...d.grammar.map(grammarCard));if(!d.grammar.length)$('article-grammar').append(node('p','empty-note','本篇未列出单独的核心语法。'));$('vocabulary-body').replaceChildren();for(const v of d.vocabulary){const row=node('tr');for(const key of ['korean','chinese','expression']){const c=node('td');rich(c,v[key]);if(key==='korean')c.lang='ko';row.append(c)}$('vocabulary-body').append(row)}const links=$('book-links');links.replaceChildren();for(const [label,name] of [['本级学习册',`韩语${a.level}级-对话与文章学习册.pdf`],['本级语法册',`韩语${a.level}级-语法汇编.pdf`],['3–6级语法总汇','韩语语法汇编.pdf']]){const link=node('a','',label+' ↗');link.href='books/'+name;link.target='_blank';link.rel='noopener';links.append(link)}buttons.forEach((b,i)=>{b.querySelectorAll('.sentence-analysis,.sentence-note').forEach(e=>e.remove());const s=d.sentences[i];if(s.breakdown){const p=node('span','sentence-analysis');p.append(node('strong','','拆解：'));rich(p,s.breakdown);b.append(p)}if(s.note){const p=node('span','sentence-note');rich(p,s.note);b.append(p)}for(const note of s.legacy_notes||[]){const p=node('span','sentence-note');rich(p,note);b.append(p)}});$('open-grammar').classList.remove('selected')}
function renderGrammar(){const q=$('grammar-search').value.trim().toLowerCase(),cat=$('grammar-category').value;const rows=grammars.filter(g=>(!cat||g.category===cat)&&[g.form,g.connection,g.meaning,g.example,g.note].join(' ').toLowerCase().includes(q));$('grammar-results').replaceChildren(...rows.map(grammarCard));$('grammar-count').textContent=rows.length+' / '+grammars.length+' 条';if(!rows.length)$('grammar-results').append(node('p','empty-note','没有匹配的语法，试试其他关键词。'))}
$('open-grammar').onclick=()=>{stop();document.body.classList.add('grammar-view');$('reader').hidden=true;$('grammar-browser').hidden=false;$('open-grammar').classList.add('selected');document.body.classList.remove('nav-open');renderGrammar();window.scrollTo(0,0)};
$('return-reading').onclick=()=>{renderStudy(DATA);window.scrollTo(0,0)};
for(const cat of [...new Set(grammars.map(g=>g.category))]){const o=node('option','',cat);o.value=cat;$('grammar-category').append(o)}
$('grammar-search').oninput=renderGrammar;$('grammar-category').onchange=renderGrammar;
$('analysis').onchange=()=>document.body.classList.toggle('hide-analysis',!$('analysis').checked);
document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>jump(b.dataset.jump));
renderStudy(DATA);
